### ISSUE TITLE
Provide a easy way to provide private registry configuration for k8s cluster creation

### ISSUE THREAD

**Issue by savmickael** [CS-SI/SafeScale#92] opened 2021-05-26 09:47 UTC
Currently it is not possible to create a k8s cluster with a too large number of nodes due to [dockerhub pull rate limit](https://www.docker.com/increase-rate-limits).

The creation failed due to the fact that k8s need to pull calico image from dockerhub.

```
Warning  Failed   35m (x36 over 3h15m)     kubelet  Failed to pull image "calico/node:v3.10.4": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Normal   Pulling  25m (x38 over 3h15m)     kubelet  Pulling image "calico/node:v3.10.4"
  Normal   BackOff  5m25s (x831 over 3h15m)  kubelet  Back-off pulling image "calico/node:v3.10.4"
  Warning  Failed   15s (x854 over 3h15m)    kubelet  Error: ImagePullBackOff
```

To overpass this dockerhub limitation, a solution is to use a private registry to store the needed image.

However it is currently not easy to pass these information to k8s via safescale. You need to connect manually to the master to update k8s config to set this private registry.

From my point of view it is a blocking issue to use safescale to create and manage large k8s cluster.

**Comment by vplanche-cssi** [comment] 2021-05-31 15:20
Considered as a duplicate of issue #91.

**Closed by vplanche-cssi** 2021-05-31 15:20 UTC
