### ISSUE TITLE
[Bug] [v21.11.0] Disable Flag gateway-failover not working correctly

### ISSUE THREAD

**Issue by vvignaux** [CS-SI/SafeScale#173] opened 2022-03-29 13:52 UTC
version: v21.11.0

When trying to create a cluster with the following command:

`safescale cluster create callisto --complexity=Normal --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30" --disable gateway-failover`

The creation fails with the following message:

`ERROR   [2022-03-29 11:36:47.170][error][ 4006] We have a primary gateway with name gw-callisto and id 19bac927-a53c-4391-8844-c5af6a09629b and a secondary gateway with name gw-callisto and id 19bac927-a53c-4391-8844-c5af6a09629b`

The relevant logs section: 
[safescale.log](https://github.com/CS-SI/SafeScale/files/8372035/safescale.log)

**Comment by oscarpicas** [comment] 2022-03-29 14:24
It's not a bug.
It's a "feature" of urfave/v2 (the lib used by SafeScale to process user input)

The name of the cluster MUST be the LAST parameter of the command line
you are writing this command:

`
safescale cluster create callisto --complexity=Normal --flavor=K8S --gw-sizing="template=d2-2" --mastersizing="template=b2-7" --node-sizing="template=b2-30" --disable gateway-failover
`

but safescaled SEES this command (it stops reading after the cluster name):

`
safescale cluster create callisto
`

if you want to take into account all parameters you should write (notice the position of the cluster's name):

`
safescale cluster create --complexity=Normal --flavor=K8S --gw-sizing="template=d2-2" --mastersizing="template=b2-7" --node-sizing="template=b2-30" --disable gateway-failover callisto
`

future releases of SafeScale will issue a warning about this (saying that running the command without modifications such and such parameters are IGNORED)

**Comment by oscarpicas** [comment] 2022-03-29 15:04
If the problem is the log message "We have a primary gateway etc. etc." it could have been a Warning message too, we just wanted to make sure this kind of issue was displayed, it doesn't stop the cluster creation process.

But, if the problem is the "stuck here", and by that you mean "stuck there forever", then yes, it must NOT happen, and it's some kind of deadlock; if you confirm it's the latter we will retag the issue as a "bug" and will look into it

**Comment by oscarpicas** [comment] 2022-03-29 15:50
Please, try again, this time with the following command (forcing a cidr):

`
./safescale cluster create --complexity=Normal --cidr "192.168.27.0/24" --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30" --disable gateway-failover callisto
`

and let us know if it works.

**Comment by oscarpicas** [comment] 2022-03-29 20:39
It seems commit https://github.com/CS-SI/SafeScale/commit/384f482ae3d358a0768a2bd0e78ad2c7ecd3f458 introduced a severe regression, develop branch has several deadlocks right now.

This will be fixed next week.
In the meantime you should use branch release/v21.11, using this branche previous cluster creation command (callisto) works.

In order to build release/v21.11 based binaries:
`
git clone https://github.com/CS-SI/SafeScale --depth 1 -b release/v21.11
cd SafeScale
./create-local-docker.sh
`

and the binaries should be in the ./exported directory

**Comment by vvignaux** [comment] 2022-03-30 08:23
Forcing the CIDR sadly didn't improve the outcome, with a deadlock still being present. Thanks for the recommendation, but I also need the corrections from #149. It works but I still encounter timeouts issues on the cluster creation process, I will try without this flag and increasing the timeouts for the time being. Thank you a lot for your help

**Comment by oscarpicas** [comment] 2022-03-30 09:00
Corrections from #149 are already on release/v21.11; recreating the binaries with branch release/v21.11 works with the following command (tested yesterday), and uses the right templates too:
`
safescale cluster create --complexity=Normal --cidr "192.168.27.0/24" --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30" --disable gateway-failover callisto
`

**Comment by vvignaux** [comment] 2022-03-31 07:01
In the end I managed to have the cluster creation successful trying both the release and the latest develop after trying various timeout modification, and both seems to be working. Thanks again

**Comment by vplanche-cssi** [comment] 2022-03-31 14:49
Fixed in develop. Will be included in upcoming release v21.11.1.

**Closed by vplanche-cssi** 2022-03-31 14:49 UTC
Labels: bug
